### ISSUE TITLE
TypeError in Colab demo 

### ISSUE THREAD

**Issue by wandrzej** [ermongroup/SDEdit#2]
All 3 blocks for image generation produce this error:
`TypeError: image_editing_denoising_step_flexible_mask() got an unexpected keyword argument 'return_pred_xstart'`

**Comment by weihaox** [comment]
Delete line [106](https://github.com/ermongroup/SDEdit/blob/main/colab_utils/utils.py#L106) `return_pred_xstart=False` in colab_utils/utils.py. 


<img width="601" alt="截屏2021-08-05 下午11 29 33" src="https://user-images.githubusercontent.com/54136324/128377426-00af5210-8d64-419d-aa03-c5b52855ae81.png">

**Comment by AK391** [comment]
@weihaox still getting the error did you restart the notebook?

**Comment by weihaox** [comment]
> @weihaox still getting the error did you restart the notebook?

Yes, you need to restart the notebook. It seems that modifications in colab would take some time to become effective. You can add some print command to see if the modified script is working.

**Comment by chenlin9** [comment]
Thank you for starting the discussion. The issue in the notebook should be fixed now. 
We updated colab_utils/utils.py line 106, "return_pred_xstart=False" is now removed. 
Let us know if there are any other issues with the notebook! Thank you!

**Comment by chenlin9** [comment]
> Delete line [106](https://github.com/ermongroup/SDEdit/blob/main/colab_utils/utils.py#L106) `return_pred_xstart=False` in colab_utils/utils.py.
> 
> <img alt="截屏2021-08-05 下午11 29 33" width="601" src="https://user-images.githubusercontent.com/54136324/128377426-00af5210-8d64-419d-aa03-c5b52855ae81.png">

Yeah, that seems to be the issue. Thank you for pointing that out!
