### ISSUE TITLE
Error while Downloading Pre-trained Model Weights

### ISSUE THREAD

**Issue by AlonzoLeeeooo** [ermongroup/SDEdit#20]
Hi,

Thank you for the code implementation of the nice work! I was encountering an error while trying to download your pre-trained model weights. Here is the error:

<img width="908" alt="image" src="https://github.com/ermongroup/SDEdit/assets/68578066/beffa7f7-7f39-40b7-bc3c-49877467f2d1">

Could you please fix it? Thanks in advance!

Best,

**Comment by dt990pro** [comment]
I tried this one. It works.
https://github.com/ermongroup/ddim/blob/main/functions/ckpt_util.py#L12

They said they use the model from DDIM.

**Comment by AlonzoLeeeooo** [comment]
> I tried this one. It works. https://github.com/ermongroup/ddim/blob/main/functions/ckpt_util.py#L12
> 
> They said they use the model from DDIM.

Thanks for replying!
