### ISSUE TITLE
Pretrained models now missing

### ISSUE THREAD

**Issue by hecoding** [ermongroup/SDEdit#23]
Hi @chenlin9 
Great work, but seems that all pretrained checkpoints are down, since all rely on AWS, i.e.:
`https://image-editing-test-12345.s3-us-west-2.amazonaws.com/checkpoints/bedroom.ckpt`

Several works depend on these, would you mind uploading them again?

Personally, I'm looking for LSUN Bedrooms, but I see a lot of people requesting [CelebA-HQ](https://drive.google.com/file/d/1wSoA5fm_d6JBZk4RZ1SzWLMgev4WqH21/view?usp=share_link) too.

Thanks.

**Comment by chenlin9** [comment]
Hello, we use the same checkpoint as DDIM https://github.com/ermongroup/ddim

**Comment by hecoding** [comment]
Right, I was wondering that. Thanks for the quick answer!

For future reference, [here](https://github.com/ermongroup/ddim/blob/main/functions/ckpt_util.py) they are 
```python
URL_MAP = {
    "cifar10": "https://heibox.uni-heidelberg.de/f/869980b53bf5416c8a28/?dl=1",
    "ema_cifar10": "https://heibox.uni-heidelberg.de/f/2e4f01e2d9ee49bab1d5/?dl=1",
    "lsun_bedroom": "https://heibox.uni-heidelberg.de/f/f179d4f21ebc4d43bbfe/?dl=1",
    "ema_lsun_bedroom": "https://heibox.uni-heidelberg.de/f/b95206528f384185889b/?dl=1",
    "lsun_cat": "https://heibox.uni-heidelberg.de/f/fac870bd988348eab88e/?dl=1",
    "ema_lsun_cat": "https://heibox.uni-heidelberg.de/f/0701aac3aa69457bbe34/?dl=1",
    "lsun_church": "https://heibox.uni-heidelberg.de/f/2711a6f712e34b06b9d8/?dl=1",
    "ema_lsun_church": "https://heibox.uni-heidelberg.de/f/44ccb50ef3c6436db52e/?dl=1",
}
```
Also available in Diffusers https://huggingface.co/models?library=diffusers&sort=downloads&search=ddpm

Cheers

**Comment by haooxia** [comment]
Thanks for the pre-trained model link, besides, did you know of alternative links for these data https://github.com/ermongroup/SDEdit/blob/66a5e44db6c36d5979c323781675d67117c0fb04/functions/process_data.py#L8-L12 (they also failed)

**Comment by stephenivy07** [comment]
> Thanks for the pre-trained model link, besides, did you know of alternative links for these data
> 
> https://github.com/ermongroup/SDEdit/blob/66a5e44db6c36d5979c323781675d67117c0fb04/functions/process_data.py#L8-L12
> 
> (they also failed)

Got the same problem. Did you solve it?
