### ISSUE TITLE
Generate hd images

### ISSUE THREAD

**Issue by Rm1n90** [ermongroup/SDEdit#7]
Hey @chenlin9 and @junyanz, 
Awesome work! I have a question about training and generating high-resolution images (1024x1024). 

How can I train on FFHQ or CelebA-HQ. I have looked for the config file but couldn't find any config for training 1024x1024 resolution. All the config files are for images with sizes 256x256. I would like to train the model on my custom dataset to generate 1024x1024 images. Would it be possible to provide the config file for CelebA-HQ or can you elaborate on how can I train for such a dataset to generate 1024x1024?

Thanks!

**Comment by chenlin9** [comment]
Thank you for the question! 

For 1024x1024 resolution images, we use the pretrained model from this repository
https://github.com/yang-song/score_sde_pytorch
More training details can also be found in this repository.
